Dockerfile 구성
 - FROM : 빌드할 베이스 이미지 지정
 - RUN : 컨테이너에서 실행할 명령어를 지정(빌드할 때 실행)
 - ADD : 컨테이너에 배치할 파일이나 디렉토리 지정
 - CMD : 컨테이너가 시작할 때 실행할 명령어를 지정
 - ENTRYPOINT : CMD와 동일하나 param 값을 대체할 수 없음
 - LABEL : key-value 의 메타데이터를 이미지에 추가
 - ENV : 환경변수 지정
 - VOLUME : 컨테이너 내의 특정 디렉토리 지정
